# Lecture 생성
POST http://127.0.0.1:8000/lecture
Content-Type: multipart/form-data; boundary=boundary
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJFMFVScDZ5SW5sUXNtRnU4YW5uUm5TU2NBNFQyIiwibmFtZSI6IuyYpOyKueykgCIsImVtYWlsIjoib3NqdW55MTFAZ21haWwuY29tIiwicHJvZmlsZUltYWdlVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EtL0FPaDE0R2hSOXFSaXdIQWozeWxiekt6WHpLY3RHaHh4Z2pERWZNYmpkNHBNSDdvIiwiaWF0IjoxNTk1MTQzNzY1LCJleHAiOjE1OTU3NDg1NjV9.mbpl4v-2GlspCmQzD5Wl1h9w8A4r6wQPEraYCGnF1-U

--boundary
Content-Disposition: form-data; name="title";

강의 제목 1

--boundary
Content-Disposition: form-data; name="description";

이것은 강의에 대한 설명입니당

--boundary
Content-Disposition: form-data; name="lectureMainImage"; filename="mainimage.jpg"
Content-Type: image/jpg

< /Users/dsa28s/Downloads/IMG_0308.jpg

--boundary--


###

# 차시 생성
POST http://127.0.0.1:8000/lecture/5f12fabea09e7b05995870f0/lesson
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title";

차시 제목 1

--boundary
Content-Disposition: form-data; name="description";

이것은 차시에 대한 설명입니당

--boundary
Content-Disposition: form-data; name="content";

프론트에서 준 타임라인 콘텐츠 입니당

--boundary
Content-Disposition: form-data; name="duration";

1234567

--boundary
Content-Disposition: form-data; name="lessonVideo"; filename="mainimage.jpg"
Content-Type: video/mp4

< /Users/dsa28s/Downloads/IMG_0308.jpg

--boundary--


###

# 강의 목록
GET http://127.0.0.1:8000/lecture
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJFMFVScDZ5SW5sUXNtRnU4YW5uUm5TU2NBNFQyIiwibmFtZSI6IuyYpOyKueykgCIsImVtYWlsIjoib3NqdW55MTFAZ21haWwuY29tIiwicHJvZmlsZUltYWdlVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EtL0FPaDE0R2hSOXFSaXdIQWozeWxiekt6WHpLY3RHaHh4Z2pERWZNYmpkNHBNSDdvIiwiaWF0IjoxNTk1MTQzNzY1LCJleHAiOjE1OTU3NDg1NjV9.mbpl4v-2GlspCmQzD5Wl1h9w8A4r6wQPEraYCGnF1-U
