# Lecture 생성
POST http://127.0.0.1:8000/lecture
Content-Type: multipart/form-data; boundary=boundary
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJKajV4U1l4QjJvaHpiVU16R1ROaU80RGtqZzgyIiwibmFtZSI6IlNhbmdodW4gTGVlIiwiZW1haWwiOiJzYW5naHVuQHNjYXR0ZXJsYWIuY28ua3IiLCJwcm9maWxlSW1hZ2VVcmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHalkwREtOMzZwODJ0MjNma3pjQ0ZMRVZLMEZ5SldpbVdwNEJHb2oiLCJpYXQiOjE1OTUxNTgwODEsImV4cCI6MTU5NTc2Mjg4MX0.zLib2f36v9YJefpUZJC02ikjbAzwIG4wQqZdpd5EQqI

--boundary
Content-Disposition: form-data; name="title";

[입문~활용] 데이터 분석을 위한 SQL 시리즈 3종

--boundary
Content-Disposition: form-data; name="description";

SQL 기초 이론을 배우고, 해커랭크 문제 10개를 함께 풀어봅니다.

--boundary
Content-Disposition: form-data; name="lectureMainImage"; filename="mainimage.jpg"
Content-Type: image/png

< /Users/dsa28s/Desktop/roadmap-92.png

--boundary--


###

# 차시 생성
POST http://127.0.0.1:8000/lecture/5f142e5292dfd00070f9d0a0/lesson
Content-Type: multipart/form-data; boundary=boundary
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJKajV4U1l4QjJvaHpiVU16R1ROaU80RGtqZzgyIiwibmFtZSI6IlNhbmdodW4gTGVlIiwiZW1haWwiOiJzYW5naHVuQHNjYXR0ZXJsYWIuY28ua3IiLCJwcm9maWxlSW1hZ2VVcmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHalkwREtOMzZwODJ0MjNma3pjQ0ZMRVZLMEZ5SldpbVdwNEJHb2oiLCJpYXQiOjE1OTUxNTgwODEsImV4cCI6MTU5NTc2Mjg4MX0.zLib2f36v9YJefpUZJC02ikjbAzwIG4wQqZdpd5EQqI

--boundary
Content-Disposition: form-data; name="title";

과연 차시가 잘 될까?

--boundary
Content-Disposition: form-data; name="description";

이거 나오면 진짜 킹왕짱 백엔드 잘한거다;; 준비된 남자 오!승!준!

--boundary
Content-Disposition: form-data; name="content";

{'sdfsdf'}

--boundary
Content-Disposition: form-data; name="duration";

24000

--boundary
Content-Disposition: form-data; name="lessonVideo"; filename="mainimage.jpg"
Content-Type: video/mp4

< /Users/dsa28s/Downloads/index.webm

--boundary--


###

# 강의 목록
GET http://127.0.0.1:8000/lecture
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJFMFVScDZ5SW5sUXNtRnU4YW5uUm5TU2NBNFQyIiwibmFtZSI6IuyYpOyKueykgCIsImVtYWlsIjoib3NqdW55MTFAZ21haWwuY29tIiwicHJvZmlsZUltYWdlVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EtL0FPaDE0R2hSOXFSaXdIQWozeWxiekt6WHpLY3RHaHh4Z2pERWZNYmpkNHBNSDdvIiwiaWF0IjoxNTk1MTQzNzY1LCJleHAiOjE1OTU3NDg1NjV9.mbpl4v-2GlspCmQzD5Wl1h9w8A4r6wQPEraYCGnF1-U


###

# 차시 목록
GET http://127.0.0.1:8000/lecture/5f13f6a815e1f801d9275da4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJFMFVScDZ5SW5sUXNtRnU4YW5uUm5TU2NBNFQyIiwibmFtZSI6IuyYpOyKueykgCIsImVtYWlsIjoib3NqdW55MTFAZ21haWwuY29tIiwicHJvZmlsZUltYWdlVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EtL0FPaDE0R2hSOXFSaXdIQWozeWxiekt6WHpLY3RHaHh4Z2pERWZNYmpkNHBNSDdvIiwiaWF0IjoxNTk1MTQzNzY1LCJleHAiOjE1OTU3NDg1NjV9.mbpl4v-2GlspCmQzD5Wl1h9w8A4r6wQPEraYCGnF1-U
